//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestForm.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestForm.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на R 30 2.5 10 27.5 0 Алюминий Алюминий
        ///R 2.5 30 40 0 0 Алюминий Алюминий
        ///R 75  8.5 42.5 0 0 Алюминий Алюминий
        ///R 2.5 30 117.5 0 0 Алюминий Алюминий
        ///R 30 2.5 120 27.5 0 Алюминий Алюминий
        ///R 2.5 8 42.5 14.5 0 Алюминий Алюминий
        ///R 75  2.5 42.5 22.5 0 Алюминий Алюминий
        ///R 2.5 8 115 14.5 0 Алюминий Алюминий
        ///R 160 2 0 30 0 Дерево Алюминий
        ///R 160 10 0 32 0 Алюминий Алюминий
        ///R 160 6 0 42 0 Алюминий Алюминий
        ///R 160 10 0 48 0 Алюминий Алюминий
        ///R 160 6 0 58 0 Алюминий Алюминий
        ///R 160 10 0 64 0 ППУ Алюминий
        ///R 160  [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string TextFile1 {
            get {
                return ResourceManager.GetString("TextFile1", resourceCulture);
            }
        }
    }
}
